import { StyleSheet } from 'react-native';

const fonts = StyleSheet.create({
  textCircularColorBlue: {
    color: '#476ee6',
    fontFamily: 'Poppins-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.72,
  },
  textCircularSmallBlue: {
    color: '#476ee6',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
    
  },
  textCircularColorBlueBold: {
    color: '#476ee6',
    fontFamily: 'Poppins-Regular',
    fontSize: 25,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24.286,
    letterSpacing: 0.101,
  },
  textCircularSmallBlueCategories: {
    color: '#476ee6',
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
  },
  textCircularSmallBlueCategoriesBold: {
    color: '#476ee6',
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0.075,
  },
  textCircularColorBlueTitle: {
    color: '#476ee6',
    fontFamily: 'Poppins-Regular',
    fontSize: 30,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24.286,
    letterSpacing: 0.101,
  },
  textCircularLabel: {
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 18.215,
    letterSpacing: 0.202,
  },
  textCircularColorBlackCardContent: {
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  textCircularSmallBoldBlack: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 20,
  },
  textCircularColorBlackBigCard: {
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: '800',
    lineHeight: 20,
    letterSpacing: 0.5
  },
  
  textCircularPlaceholder: {
    color: '#a0a0a0',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
  },
  textCircularSideMenuColorGrey: {
    color: '#787486',
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 20,
  },
  textCircularButtonColorFFF: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  textCircularColorWhiteTitleCard: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 24,
    letterSpacing: 0.3,
  },
  textCircularSmallRed: {
    color: '#ff6666',
    maxWidth: 300,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '500',
  },
});

export default fonts;